/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import com.wemboo.boilerplate.beans.SessionStateBean;

public class SampleTest {
    @Test public void testAppHasAGreeting() {
        SessionStateBean classUnderTest = new SessionStateBean();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}